# Linear Algebra

In [1]:
import torch

In [2]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [3]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [4]:
# exponentition per element
x ** y

tensor([ 1.,  4., 16., 64.])

In [5]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [6]:
# tensor concat by row and column
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2., 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [7]:
# in-place memory
z = torch.zeros_like(y)
print("id(z) = {}".format(id(z)))
z[:] = x + y
print("id(z) = {}".format(id(z)))

id(z) = 140189474395648
id(z) = 140189474395648


In [8]:
before = id(x)
x += y
id(x) == before

True

In [9]:
x.shape

torch.Size([3, 4])

In [10]:
x.T.shape

torch.Size([4, 3])

In [11]:
B = x.clone()

In [12]:
x

tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]])

In [13]:
x.sum(axis=0)

tensor([19., 21., 27., 29.])

In [14]:
x.sum(axis=1)

tensor([16., 32., 48.])

In [17]:
x = torch.arange(0, 4.)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [18]:
A = torch.ones(3, 4)
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

# Calculus